### ISSUE TITLE
Update the shortlist in worker-classes for `taskcluster/configs/config.prod.yml`

### ISSUE THREAD

**Issue by gregtatum** [mozilla/translations#1103]
> @gregtatum should `shortlist` be renamed to the new stage name here: `distillation-corpus-build-shortlist` 

 _Originally posted by @eu9ene in [be3aafb](https://github.com/mozilla/translations/commit/be3aafb21402090600ce2dc63c4967d77784e8e5#r156089374)_

This one was missed:

```yml
  worker-classes:
    default: gcp-spot
    # long-running tasks that don't support restarts with continuation like training tasks
    corpus-align-parallel: gcp-standard
    corpus-align-backtranslations: gcp-standard
    corpus-align-distillation: gcp-standard
    distillation-corpus-build-shortlist: gcp-standard
```
